name: Team lab 2

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: make -C ../../ out/example
      - name: test
        run: make -C ../../ test
      - name: clean
        run: make -C ../../ clean
