name: Team lab 2

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: pwd
             make out/example
      - name: test
        run: make test
      - name: clean
        run: pwd
             make clean