name: Team lab 2

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # - name: test
      #   run: make test
      - name: build
        run: make out/example
      - name: clean
        run: make clean